# Generated by Django 5.2.6 on 2025-12-24 07:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('applicable_grades', models.CharField(choices=[('1-3', 'Grades 1-3'), ('4-6', 'Grades 4-6'), ('7-10', 'Grades 7-10'), ('ALL', 'All Grades')], max_length=10)),
                ('is_core', models.BooleanField(default=True)),
                ('is_optional', models.BooleanField(default=False, help_text='e.g., Arabic Language, Islamic Values')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Learning Area',
                'verbose_name_plural': 'Learning Areas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('lrn', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Learner Reference Number')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('name_extension', models.CharField(blank=True, help_text='Jr, Sr, I, II, III', max_length=10)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('credential_presented', models.CharField(blank=True, choices=[('KINDER_PROGRESS', 'Kinder Progress Report'), ('ECCD_CHECKLIST', 'ECCD Checklist'), ('KINDER_CERTIFICATE', 'Kindergarten Certificate of Completion'), ('PEPT', 'PEPT Passer'), ('OTHER', 'Other Credential')], max_length=20, null=True)),
                ('other_credential', models.CharField(blank=True, max_length=200)),
                ('pept_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pept_date', models.DateField(blank=True, null=True)),
                ('pept_testing_center', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(choices=[(1, 'Grade 7'), (2, 'Grade 8'), (3, 'Grade 9'), (4, 'Grade 10')])),
                ('section', models.CharField(max_length=50)),
                ('school_year', models.CharField(help_text='Format: 2024-2025', max_length=9)),
                ('adviser_teacher', models.CharField(max_length=200)),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('PROMOTED', 'Promoted'), ('RETAINED', 'Retained')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='depedsfportal.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='depedsfportal.student')),
            ],
            options={
                'verbose_name': 'Academic Record',
                'verbose_name_plural': 'Academic Records',
                'ordering': ['-school_year', 'grade_level'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quarter_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quarter_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quarter_4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('needs_remedial', models.BooleanField(default=False)),
                ('remedial_conducted_from', models.DateField(blank=True, null=True)),
                ('remedial_conducted_to', models.DateField(blank=True, null=True)),
                ('remedial_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recomputed_final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='depedsfportal.academicrecord')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='depedsfportal.learningarea')),
            ],
            options={
                'verbose_name': 'Subject Grade',
                'verbose_name_plural': 'Subject Grades',
                'ordering': ['learning_area__order', 'learning_area__name'],
            },
        ),
        migrations.AddIndex(
            model_name='academicrecord',
            index=models.Index(fields=['student', 'school_year'], name='depedsfport_student_e7611a_idx'),
        ),
        migrations.AddIndex(
            model_name='academicrecord',
            index=models.Index(fields=['grade_level', 'school_year'], name='depedsfport_grade_l_fb501c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together={('student', 'grade_level', 'school_year')},
        ),
        migrations.AddIndex(
            model_name='subjectgrade',
            index=models.Index(fields=['academic_record', 'learning_area'], name='depedsfport_academi_74f668_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectgrade',
            unique_together={('academic_record', 'learning_area')},
        ),
    ]
