# Generated by Django 4.2.27 on 2025-12-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depedsfportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200, verbose_name='House No./Street'),
        ),
        migrations.AddField(
            model_name='student',
            name='barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City/Municipality'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='Philippines', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
