# Generated by Django 4.2.27 on 2025-12-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depedsfportal', '0002_student_address_line1_student_barangay_student_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('TRANSFERRED', 'Transferred Out'), ('DROPPED', 'Dropped')], default='ENROLLED', max_length=20),
        ),
    ]
