# Generated by Django 4.2.27 on 2025-12-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depedsfportal', '0003_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
    ]
