# Generated by Django 4.2.27 on 2025-12-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depedsfportal', '0004_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='grade_level',
            field=models.IntegerField(choices=[(7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10')]),
        ),
        migrations.AlterField(
            model_name='learningarea',
            name='applicable_grades',
            field=models.CharField(choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('ALL', 'All Grades')], max_length=10),
        ),
    ]
