# Generated by Django 4.2.27 on 2025-12-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depedsfportal', '0005_alter_academicrecord_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningarea',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='learningarea',
            unique_together={('code', 'applicable_grades')},
        ),
    ]
