# Generated by Django 4.2.27 on 2025-12-26 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depedsfportal', '0008_finalize_section_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='adviser_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
