# Generated by Django 4.2.27 on 2025-12-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depedsfportal', '0009_alter_academicrecord_adviser_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_students',
            field=models.IntegerField(blank=True, default=45, help_text='Maximum number of students allowed in this section', null=True),
        ),
    ]
