# Generated by Django 4.2.27 on 2025-12-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depedsfportal', '0010_add_section_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(help_text='Format: 2024-2025', max_length=9, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Mark this as the current active academic year')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
    ]
