# Generated by Django 4.2.27 on 2025-12-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depedsfportal', '0011_add_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='depedsfportal.section'),
        ),
    ]
