"""
Django settings for SmartForms project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+@62(skc)m=(o+d71t%i48n6%vdgv)i9$=3jeo65pst^+e*0p_"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "smartdepedforms.onrender.com"]


# Application definition

INSTALLED_APPS = [
    "depedsfportal",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", #render
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SmartForms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "depedsfportal.context_processors.school_context",
            ],
        },
    },
]

WSGI_APPLICATION = "SmartForms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    #Local Development
   # "default": {
       # 'ENGINE': 'django.db.backends.sqlite3',
      #  'NAME': BASE_DIR / 'db.sqlite3',
      #  "ENGINE": "django.db.backends.postgresql",
      #  "NAME": "SmartFormsDB",
     #   "USER": "postgres",
     #   "PASSWORD": "admin12345",
     #   "HOST": "localhost",
     #   "PORT": "5432",
   # }

    #Render Deployment
     'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smartforms_depedsf',
        'USER': 'smartforms_depedsf_user',
        'PASSWORD': 'pLHvFSrneNHIk6LAswLpLXIp7gSCCo0a',
        'HOST': 'dpg-d56l343uibrs739m9ta0-a',
        'PORT': '5432',
    }

     # Using Render's DATABASE_URL environment variable
    #'default':{
    #   'ENGINE': 'django.db.backends.postgresql',
    #    'NAME': 'smartforms_depedsf',  # database name
    #    'USER': 'smartforms_depedsf_user',  # username
    #    'PASSWORD': 'pLHvFSrneNHIk6LAswLpLXIp7gSCCo0a',  # password
    #    'HOST': 'dpg-d56l343uibrs739m9ta0-a.virginia-postgres.render.com',  # host
    #    'PORT': '5432',  # default PostgreSQL port
    #}
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

JAZZMIN_SETTINGS = {
    "site_title": "DEPEDSF10",
    "site_header": "Deped SF10",
    "site_brand": "DEPEDSF10",
    "welcome_sign": "Welcome to Deped SF10 Admin",
    "site_logo": "logo.png",
    "copyright": "ArSystems",
}

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"
LOGIN_URL = "/login/"
